// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProjectFromPath(arg1:string):Promise<main.ProjectState>;

export function AddProjectSelectionsToTodo(arg1:string,arg2:Array<main.TodoProjectSelection>):Promise<main.ProjectState>;

export function AddProjectToTodo(arg1:string,arg2:string):Promise<main.ProjectState>;

export function AddProjectsToTodo(arg1:string,arg2:Array<string>):Promise<main.ProjectState>;

export function AddProjectsToTodoWithBranches(arg1:string,arg2:Array<string>,arg3:Record<string, string>):Promise<main.ProjectState>;

export function ChangeTodoStatus(arg1:string,arg2:string):Promise<main.ProjectState>;

export function ClaudeStatusHookState(arg1:string):Promise<main.ClaudeHookState>;

export function ClearRecentWorkspaces():Promise<main.WorkspaceState>;

export function CloseWorkspace():Promise<main.ProjectState>;

export function CompleteTodo(arg1:string):Promise<main.ProjectState>;

export function CreateProjectFromDialog():Promise<main.ProjectImportResult>;

export function CreateTaskTerminal(arg1:string,arg2:number,arg3:number):Promise<main.ProjectState>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<main.ProjectState>;

export function CreateTodo(arg1:main.CreateTodoRequest):Promise<main.ProjectState>;

export function CreateTodoTerminal(arg1:string,arg2:number,arg3:number):Promise<main.ProjectState>;

export function CreateWorkspaceTerminal(arg1:number,arg2:number):Promise<main.ProjectState>;

export function DeleteCompletedTodos(arg1:Array<string>):Promise<main.ProjectState>;

export function DeleteProject(arg1:string):Promise<main.ProjectState>;

export function DeleteProjects(arg1:Array<string>):Promise<main.ProjectState>;

export function DeleteTerminal(arg1:string):Promise<main.ProjectState>;

export function DeleteTodo(arg1:string):Promise<main.ProjectState>;

export function DeleteTodoProjectUIState(arg1:Array<string>):Promise<void>;

export function DetectTerminalShell():Promise<main.TerminalShellSetting>;

export function EnsureClaudeStatusHook(arg1:string):Promise<void>;

export function GetCompletedTodoProjectMergeStatuses(arg1:Array<main.CompletedTodoProjectMergeStatusRequest>):Promise<Array<main.CompletedTodoProjectMergeStatus>>;

export function GetProjectGitStatus(arg1:string):Promise<main.GitStatus>;

export function GetShellStatus(arg1:string):Promise<main.ShellStatus>;

export function GetTodoGitStatus(arg1:string):Promise<main.GitStatus>;

export function GetTodoProjectGitStatus(arg1:string):Promise<main.GitStatus>;

export function ImportProjectFromPath(arg1:string):Promise<main.ProjectImportResult>;

export function ImportProjectsFromParentDirectory(arg1:string):Promise<main.ProjectState>;

export function ImportProjectsFromParentDirectoryDialog():Promise<main.ProjectState>;

export function InitializeGitRepositoryAndImportProject(arg1:string):Promise<main.ProjectState>;

export function InitializeProjectGitRepository(arg1:string):Promise<void>;

export function ListProjectBranches(arg1:string):Promise<Array<string>>;

export function ListProjects():Promise<main.ProjectState>;

export function LoadTerminalSettings():Promise<main.TerminalSettingsState>;

export function LoadTodoInitializationFiles():Promise<Array<main.TodoInitializationFileTemplate>>;

export function LoadTodoLifecycleScripts():Promise<Array<main.TodoLifecycleScriptTemplate>>;

export function LoadTodoProjectUIState():Promise<main.TodoProjectUIStateFile>;

export function OpenRecentWorkspace(arg1:string):Promise<main.ProjectState>;

export function OpenTodoFolder(arg1:string):Promise<void>;

export function OpenTodoProjectFolder(arg1:string):Promise<void>;

export function OpenWorkspaceFromDialog():Promise<main.ProjectState>;

export function OpenWorkspaceFromPath(arg1:string):Promise<main.ProjectState>;

export function RemoveClaudeStatusHook(arg1:string):Promise<void>;

export function RemoveTodoProject(arg1:string):Promise<main.ProjectState>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RetryTodoLifecycleScript(arg1:string,arg2:string):Promise<main.ProjectState>;

export function SaveTerminalLaunchProfiles(arg1:Array<main.TerminalLaunchProfileSetting>):Promise<main.TerminalSettingsState>;

export function SaveTerminalShell(arg1:string,arg2:string):Promise<main.TerminalSettingsState>;

export function SaveTerminalTheme(arg1:string):Promise<main.TerminalSettingsState>;

export function SaveTodoInitializationFiles(arg1:Array<main.TodoInitializationFileTemplate>):Promise<main.TerminalSettingsState>;

export function SaveTodoLifecycleScripts(arg1:Array<main.TodoLifecycleScriptTemplate>):Promise<main.TerminalSettingsState>;

export function SaveTodoProjectUIState(arg1:string,arg2:main.TodoProjectUIState):Promise<void>;

export function SaveTodoSidebarWidth(arg1:number):Promise<void>;

export function SelectProject(arg1:string):Promise<main.ProjectState>;

export function SelectTerminal(arg1:string):Promise<main.ProjectState>;

export function SelectTodoProject(arg1:string):Promise<main.ProjectState>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartShell(arg1:string,arg2:number,arg3:number):Promise<main.ShellStatus>;

export function UpdateTodo(arg1:main.UpdateTodoRequest):Promise<main.ProjectState>;

export function WorkspaceState():Promise<main.WorkspaceState>;
