// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProjectFromPath(arg1:string):Promise<main.ProjectState>;

export function AddProjectToTodo(arg1:string,arg2:string):Promise<main.ProjectState>;

export function AddProjectsToTodo(arg1:string,arg2:Array<string>):Promise<main.ProjectState>;

export function ChangeTodoStatus(arg1:string,arg2:string):Promise<main.ProjectState>;

export function CompleteTodo(arg1:string):Promise<main.ProjectState>;

export function CreateProjectFromDialog():Promise<main.ProjectState>;

export function CreateTerminal(arg1:string,arg2:number,arg3:number):Promise<main.ProjectState>;

export function CreateTodo(arg1:main.CreateTodoRequest):Promise<main.ProjectState>;

export function CreateTodoTerminal(arg1:string,arg2:number,arg3:number):Promise<main.ProjectState>;

export function DeleteCompletedTodos(arg1:Array<string>):Promise<main.ProjectState>;

export function DeleteProject(arg1:string):Promise<main.ProjectState>;

export function DeleteProjects(arg1:Array<string>):Promise<main.ProjectState>;

export function DeleteTerminal(arg1:string):Promise<main.ProjectState>;

export function DeleteTodo(arg1:string):Promise<main.ProjectState>;

export function DetectTerminalShell():Promise<main.TerminalShellSetting>;

export function GetProjectGitStatus(arg1:string):Promise<main.GitStatus>;

export function GetShellStatus(arg1:string):Promise<main.ShellStatus>;

export function ImportProjectsFromParentDirectory(arg1:string):Promise<main.ProjectState>;

export function ImportProjectsFromParentDirectoryDialog():Promise<main.ProjectState>;

export function InitializeProjectGitRepository(arg1:string):Promise<void>;

export function ListProjects():Promise<main.ProjectState>;

export function LoadTerminalSettings():Promise<main.TerminalSettingsState>;

export function RemoveTodoProject(arg1:string):Promise<main.ProjectState>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveTerminalLaunchProfiles(arg1:Array<main.TerminalLaunchProfileSetting>):Promise<main.TerminalSettingsState>;

export function SaveTerminalShell(arg1:string,arg2:string):Promise<main.TerminalSettingsState>;

export function SaveTerminalTheme(arg1:string):Promise<main.TerminalSettingsState>;

export function SelectProject(arg1:string):Promise<main.ProjectState>;

export function SelectTerminal(arg1:string):Promise<main.ProjectState>;

export function SelectTodoProject(arg1:string):Promise<main.ProjectState>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartShell(arg1:string,arg2:number,arg3:number):Promise<main.ShellStatus>;

export function UpdateTodo(arg1:main.UpdateTodoRequest):Promise<main.ProjectState>;
