// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProjectFromPath(arg1:string):Promise<main.ProjectState>;

export function CreateProjectFromDialog():Promise<main.ProjectState>;

export function GetShellStatus(arg1:string):Promise<main.ShellStatus>;

export function ListProjects():Promise<main.ProjectState>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SelectProject(arg1:string):Promise<main.ProjectState>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function StartShell(arg1:string,arg2:number,arg3:number):Promise<main.ShellStatus>;
