// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectFromPath(arg1) {
  return window['go']['main']['App']['AddProjectFromPath'](arg1);
}

export function AddProjectSelectionsToTodo(arg1, arg2) {
  return window['go']['main']['App']['AddProjectSelectionsToTodo'](arg1, arg2);
}

export function AddProjectToTodo(arg1, arg2) {
  return window['go']['main']['App']['AddProjectToTodo'](arg1, arg2);
}

export function AddProjectsToTodo(arg1, arg2) {
  return window['go']['main']['App']['AddProjectsToTodo'](arg1, arg2);
}

export function AddProjectsToTodoWithBranches(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProjectsToTodoWithBranches'](arg1, arg2, arg3);
}

export function ChangeTodoStatus(arg1, arg2) {
  return window['go']['main']['App']['ChangeTodoStatus'](arg1, arg2);
}

export function ClearRecentWorkspaces() {
  return window['go']['main']['App']['ClearRecentWorkspaces']();
}

export function CloseWorkspace() {
  return window['go']['main']['App']['CloseWorkspace']();
}

export function CompleteTodo(arg1) {
  return window['go']['main']['App']['CompleteTodo'](arg1);
}

export function CreateProjectFromDialog() {
  return window['go']['main']['App']['CreateProjectFromDialog']();
}

export function CreateTaskTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTaskTerminal'](arg1, arg2, arg3);
}

export function CreateTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3);
}

export function CreateTodo(arg1) {
  return window['go']['main']['App']['CreateTodo'](arg1);
}

export function CreateTodoTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTodoTerminal'](arg1, arg2, arg3);
}

export function CreateWorkspaceTerminal(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspaceTerminal'](arg1, arg2);
}

export function DeleteCompletedTodos(arg1) {
  return window['go']['main']['App']['DeleteCompletedTodos'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProjects(arg1) {
  return window['go']['main']['App']['DeleteProjects'](arg1);
}

export function DeleteTerminal(arg1) {
  return window['go']['main']['App']['DeleteTerminal'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['App']['DeleteTodo'](arg1);
}

export function DeleteTodoProjectUIState(arg1) {
  return window['go']['main']['App']['DeleteTodoProjectUIState'](arg1);
}

export function DetectTerminalShell() {
  return window['go']['main']['App']['DetectTerminalShell']();
}

export function GetCompletedTodoProjectMergeStatuses(arg1) {
  return window['go']['main']['App']['GetCompletedTodoProjectMergeStatuses'](arg1);
}

export function GetProjectGitStatus(arg1) {
  return window['go']['main']['App']['GetProjectGitStatus'](arg1);
}

export function GetShellStatus(arg1) {
  return window['go']['main']['App']['GetShellStatus'](arg1);
}

export function ImportProjectFromPath(arg1) {
  return window['go']['main']['App']['ImportProjectFromPath'](arg1);
}

export function ImportProjectsFromParentDirectory(arg1) {
  return window['go']['main']['App']['ImportProjectsFromParentDirectory'](arg1);
}

export function ImportProjectsFromParentDirectoryDialog() {
  return window['go']['main']['App']['ImportProjectsFromParentDirectoryDialog']();
}

export function InitializeGitRepositoryAndImportProject(arg1) {
  return window['go']['main']['App']['InitializeGitRepositoryAndImportProject'](arg1);
}

export function InitializeProjectGitRepository(arg1) {
  return window['go']['main']['App']['InitializeProjectGitRepository'](arg1);
}

export function ListProjectBranches(arg1) {
  return window['go']['main']['App']['ListProjectBranches'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadTerminalSettings() {
  return window['go']['main']['App']['LoadTerminalSettings']();
}

export function LoadTodoProjectUIState() {
  return window['go']['main']['App']['LoadTodoProjectUIState']();
}

export function OpenRecentWorkspace(arg1) {
  return window['go']['main']['App']['OpenRecentWorkspace'](arg1);
}

export function OpenTodoFolder(arg1) {
  return window['go']['main']['App']['OpenTodoFolder'](arg1);
}

export function OpenTodoProjectFolder(arg1) {
  return window['go']['main']['App']['OpenTodoProjectFolder'](arg1);
}

export function OpenWorkspaceFromDialog() {
  return window['go']['main']['App']['OpenWorkspaceFromDialog']();
}

export function OpenWorkspaceFromPath(arg1) {
  return window['go']['main']['App']['OpenWorkspaceFromPath'](arg1);
}

export function RemoveTodoProject(arg1) {
  return window['go']['main']['App']['RemoveTodoProject'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveTerminalLaunchProfiles(arg1) {
  return window['go']['main']['App']['SaveTerminalLaunchProfiles'](arg1);
}

export function SaveTerminalShell(arg1, arg2) {
  return window['go']['main']['App']['SaveTerminalShell'](arg1, arg2);
}

export function SaveTerminalTheme(arg1) {
  return window['go']['main']['App']['SaveTerminalTheme'](arg1);
}

export function SaveTodoProjectUIState(arg1, arg2) {
  return window['go']['main']['App']['SaveTodoProjectUIState'](arg1, arg2);
}

export function SaveTodoSidebarWidth(arg1) {
  return window['go']['main']['App']['SaveTodoSidebarWidth'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SelectTerminal(arg1) {
  return window['go']['main']['App']['SelectTerminal'](arg1);
}

export function SelectTodoProject(arg1) {
  return window['go']['main']['App']['SelectTodoProject'](arg1);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function StartShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartShell'](arg1, arg2, arg3);
}

export function UpdateTodo(arg1) {
  return window['go']['main']['App']['UpdateTodo'](arg1);
}

export function WorkspaceState() {
  return window['go']['main']['App']['WorkspaceState']();
}
