// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectFromPath(arg1) {
  return window['go']['main']['App']['AddProjectFromPath'](arg1);
}

export function CreateProjectFromDialog() {
  return window['go']['main']['App']['CreateProjectFromDialog']();
}

export function GetShellStatus(arg1) {
  return window['go']['main']['App']['GetShellStatus'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function StartShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartShell'](arg1, arg2, arg3);
}
